# Generated by Django 3.0 on 2019-12-17 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='last_mame',
        ),
    ]
