# Generated by Django 3.0 on 2019-12-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191217_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default=0, upload_to='imagens/'),
            preserve_default=False,
        ),
    ]
