# Generated by Django 3.0 on 2019-12-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_ent',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
