# Generated by Django 3.0 on 2019-12-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_text_ent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text_ent',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
    ]
