# Generated by Django 2.0.13 on 2020-03-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200312_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.IntegerField(default=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.IntegerField(default=100),
        ),
    ]
