# Generated by Django 2.0.13 on 2020-03-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200312_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, height_field='height', upload_to='imagens/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
